name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            echo "export Go PATH"
            export PATH="/usr/local/go/bin:$PATH"

            echo "export node.js / npm via NVM"
            export NVM_DIR="$HOME/.nvm"
            
            if [ ! -s "$NVM_DIR/nvm.sh" ]; then
              echo "NVM not found at $NVM_DIR/nvm.sh"
              exit 1
            fi

            source "$NVM_DIR/nvm.sh"
            nvm use 24.21.0

            echo "==> CHECK Environment"
            whoami
            go version
            node --version
            npm --version
            make --version

            echo "==> Updating source.."
            cd /var/www/lingualearn
            git fetch origin main
            git reset --hard origin/main

            echo "==> Building backend.."
            cd /var/www/lingualearn/backend_golang

            make test
            make build

            echo "==> Building frontend.."
            cd /var/www/lingualearn/frontend_react

            npm ci
            npm run build

            echo "==> Restarting backend.."
            sudo systemctl restart lingualearn
            echo "==> [SUCCESSFUL] Restarting backend.."

            echo "==> Checking backend service.."
            sudo systemctl is-active --quiet lingualearn
            echo "==> [SUCCESSFUL] Checking backend service.."

            echo "==> Running health check.."

            sleep 2 # sementara

            curl --fail --silent --show-error \
              http://127.0.0.1:8080/api/v1/health
            echo "==> Running health check.."

            echo "==> Deployment successful.."